kibana:
  env:
    ELASTICSEARCH_URL: http://elastic-stack-elasticsearch-client.default.svc.cluster.local:9200

logstash:
  elasticsearch:
    host: elastic-stack-elasticsearch-client
  service:
    type: ClusterIP
    ports:
      syslog-tcp:
        port: 1514
        targetPort: syslog-tcp
        protocol: TCP
  ports:
    - name: syslog-tcp
      containerPort: 1514
      protocol: TCP
      
  inputs:
    main: |-
      input {
        tcp {
          port => 1514
          type => syslog
        }
      }

